name = "sales-mapper-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# If you want a custom subdomain route, we will add it later once you provide zone/subdomain
# routes = [ { pattern = "your-sub.example.com/*", zone_id = "YOUR_ZONE_ID" } ]

[[kv_namespaces]]
binding = "SESSIONS"
id = "" # to be filled by CI or after `wrangler kv:namespace create SESSIONS`

[[kv_namespaces]]
binding = "SALES_CACHE"
id = "" # to be filled by CI or after `wrangler kv:namespace create SALES_CACHE`

[vars]
# no plaintext secrets here; use wrangler secret
