name = "sales-mapper-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
account_id = "a7dd2a2bee7151ef4dc7a9f53d99b520"

# Custom domain route for emailsalesmap.beveradb.com
routes = [ { pattern = "emailsalesmap.beveradb.com/api/*" } ]

# Enable logging
[observability]
enabled = true

# KV namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "7d3aad65a5264397b9850faa2c3ae66b"

[[kv_namespaces]]
binding = "SALES_CACHE"
id = "7d67a6d777ad4507817606869fbdb06c"

[vars]
# no plaintext secrets here; use wrangler secret
