name = "sales-mapper-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Custom domain route for emailsalesmap.beveradb.com
# Note: You'll need to add this route in the Cloudflare dashboard or via API
# routes = [ { pattern = "emailsalesmap.beveradb.com/api/*" } ]

# KV namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "7d3aad65a5264397b9850faa2c3ae66b"

[[kv_namespaces]]
binding = "SALES_CACHE"
id = "7d67a6d777ad4507817606869fbdb06c"

[vars]
# no plaintext secrets here; use wrangler secret
